


comp.sistema.nombre=SATE
comp.cuenta=USERSATE
comp.semilla=semillaSATE
comp.idusuario=USERSATE

comp.llave.ruta=C://opt//software//key//sate//clavesegurades.key
#comp.llave.ruta=//opt//software//key//sate//clavesegurades.key



certificado.aldeamo.ruta=D:/certificado/certificadoAdelamo.crt
#ruta.certificado.aldeamo=//opt//software//certificado//certificadoAdelamo.crt


certificado.izipay.ruta=D:/certificado/certificadoIzipay.crt
#ruta.certificado.izipay=//opt//software//certificado//certificadoIzipay.crt

