package pe.bn.com.sate.ope.transversal.util.constantes;

import java.util.HashMap;
import java.util.Map;

public class ConstantesSeguridad {

	/***
	 * ACCESOS PARA EL USUARIO
	 */

	public static String ACCESO_OPERACIONES = "ACCESO_OPERACIONES";
	public static String ACCESO_OPERACIONES_SOLICITAR_TARJETA = "ACCESO_OPERACIONES_SOLICITAR_TARJETA";
	public static String ACCESO_OPERACIONES_CAMBIAR_ESTADO_TARJETA = "ACCESO_OPERACIONES_CAMBIAR_ESTADO_TARJETA";
	public static String ACCESO_OPERACIONES_BUSCAR_TARJETA = "ACCESO_OPERACIONES_BUSCAR_TARJETA";
	public static String ACCESO_OPERACIONES_AUTORIZAR_TARJETA = "ACCESO_OPERACIONES_AUTORIZAR_TARJETA";
	public static String ACCESO_CONSULTA = "ACCESO_CONSULTA";
	public static String ACCESO_CONSULTA_MOVIMIENTO_TARJETA = "ACCESO_CONSULTA_MOVIMIENTO_TARJETA";
	public static String ACCESO_CONSULTA_RENDICION_CUENTA_TARJETA = "ACCESO_CONSULTA_RENDICION_CUENTA_TARJETA";
	public static String ACCESO_REPORTE = "ACCESO_REPORTE";
	public static String ACCESO_REPORTE_TARJETA = "ACCESO_REPORTE_TARJETA";
	public static String ACCESO_CUENTAS = "ACCESO_CUENTAS";
	public static String ACCESO_CREAR_USUARIO = "ACCESO_CREAR_USUARIO";
	public static String ACCESO_MODIFICAR_USUARIO = "ACCESO_MODIFICAR_USUARIO";
	public static String ACCESO_ACTUALIZAR_USUARIO = "ACCESO_ACTUALIZAR_USUARIO";
	
	public static String ACCESO_CONSULTA_CLIENTE = "ACCESO_CONSULTA_CLIENTE";

	public final static Map<String, String> OPCION_ACC = new HashMap<String, String>() {
		{
			put("01S", ACCESO_OPERACIONES);
			put("02S", ACCESO_OPERACIONES_SOLICITAR_TARJETA);
			put("03S", ACCESO_OPERACIONES_CAMBIAR_ESTADO_TARJETA);
			put("04S", ACCESO_OPERACIONES_BUSCAR_TARJETA);
			put("05S", ACCESO_OPERACIONES_AUTORIZAR_TARJETA);
			put("06S", ACCESO_CONSULTA);
			put("07S", ACCESO_CONSULTA_MOVIMIENTO_TARJETA);
			put("08S", ACCESO_CONSULTA_RENDICION_CUENTA_TARJETA);
			put("09S", ACCESO_REPORTE);
			put("10S", ACCESO_REPORTE_TARJETA);
			put("11S",ACCESO_CUENTAS);
			put("12S", ACCESO_CREAR_USUARIO);
			put("13S", ACCESO_MODIFICAR_USUARIO);
			put("14S", ACCESO_ACTUALIZAR_USUARIO);
			put("15S", ACCESO_CONSULTA_CLIENTE);
		}
	};

}